### ISSUE TITLE
DefaultCPUAllocator: not enough memory: you tried to allocate 553690080 bytes. render.py

### ISSUE THREAD

**Issue by softyoda** [yzslab/nerfstudio#11]
Hi, I'm trying to render a scene on my workstation, the .ply file (30 000 iterations) wheight 700Mb.

It works fine on other scene, but this one keep crashing when loading, even when lowering camera resolution / frame duration.
Here is the full error : 

```
Traceback (most recent call last):
  File "C:\Users\Crea_Yoann\Documents\3D_Gaussian_Splatting\nerf_studio\nerfstudio\nerfstudio\scripts\gaussian_splatting\render.py", line 586, in <module>
    entrypoint()
  File "C:\Users\Crea_Yoann\Documents\3D_Gaussian_Splatting\nerf_studio\nerfstudio\nerfstudio\scripts\gaussian_splatting\render.py", line 582, in entrypoint
    tyro.cli(Commands).main()
  File "C:\Users\Crea_Yoann\Documents\3D_Gaussian_Splatting\nerf_studio\nerfstudio\nerfstudio\scripts\gaussian_splatting\render.py", line 354, in main
    pipeline = self.setup_pipeline()
  File "C:\Users\Crea_Yoann\Documents\3D_Gaussian_Splatting\nerf_studio\nerfstudio\nerfstudio\scripts\gaussian_splatting\gaussian_splatting_config.py", line 53, in setup_pipeline
    return self.config.pipeline.setup(
  File "C:\Users\Crea_Yoann\Documents\3D_Gaussian_Splatting\nerf_studio\nerfstudio\nerfstudio\configs\base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "C:\Users\Crea_Yoann\Documents\3D_Gaussian_Splatting\nerf_studio\nerfstudio\nerfstudio\pipelines\gaussian_splatting_pipeline.py", line 69, in __init__
    self.datamanager = GaussianSplattingDatamanager(kwargs["model_path"], camera_pose_transform)
  File "C:\Users\Crea_Yoann\Documents\3D_Gaussian_Splatting\nerf_studio\nerfstudio\nerfstudio\data\datamanagers\gaussian_splatting_datamanager.py", line 28, in __init__
    self.train_dataset = GaussianSplattingDataset(model_path, orientation_transform)
  File "C:\Users\Crea_Yoann\Documents\3D_Gaussian_Splatting\nerf_studio\nerfstudio\nerfstudio\data\datasets\gaussian_splatting_dataset.py", line 56, in __init__
    image_key_by_shape[shape] = torch.ones(i["height"], i["width"], 3, dtype=torch.float)
RuntimeError: [enforce fail at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 553690080 bytes.
```
After my (128gb) ram get filled

Is there any options to avoid filling the entire ram ? (the model had no issue to be trained on the same workstation (using argument --data_device cpu )

**Comment by yzslab** [comment]
Hi, try to change the [nerfstudio/data/datasets/gaussian_splatting_dataset.py#L38C13-L38C39](https://github.com/yzslab/nerfstudio/blob/dc86fc75a845e14a7363f7a33ba0b8bd833b4b49/nerfstudio/data/datasets/gaussian_splatting_dataset.py#L38C13-L38C39) to `camera_data = json.load(f)[:1]`.

**Comment by yzslab** [comment]
Hi, I have pushed a update that fix this problem. Please pull the latest commit and try again.

**Comment by softyoda** [comment]
It worked, and it is now faster now to render (it doesn't want to fill the ram anymore at initialization, it renders directly) thank you !

**Comment by yzslab** [comment]
> It worked, and it is now faster now to render (it doesn't want to fill the ram anymore at initialization, it renders directly) thank you !

Glad to hear that.

**Comment by softyoda** [comment]
Hi, maybe this modification could be useful to others ? Should I make a pull request for the change ? 

Will your viewer/rendered fork be integrated to the main once other part of 3dgs for nerfstudio (like train https://github.com/nerfstudio-project/nerfstudio/pull/2521 ) ?
