### ISSUE TITLE
can't install diff-gaussian-rasterization and simple-knn

### ISSUE THREAD

**Issue by cyrilpreiss** [yzslab/nerfstudio#5]
i can't install diff-gaussian-rasterization and simple-knn

(nerfstudio) C:\gs\nerfstudio>pip install ./submodules/simple-knn
Processing c:\gs\nerfstudio\submodules\simple-knn
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: simple-knn
  Building wheel for simple-knn (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
      running bdist_wheel
      running build
      running build_ext
      C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] Le fichier spécifié est introuvable
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\gs\nerfstudio\submodules\simple-knn\setup.py", line 21, in <module>
          setup(
        File "C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\wheel\bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 383, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, in parse
          return Version(version)
        File "C:\Users\cyril\anaconda3\envs\nerfstudio\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 196, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simple-knn
  Running setup.py clean for simple-knn
Failed to build simple-knn
ERROR: Could not build wheels for simple-knn, which is required to install pyproject.toml-based projects

**Comment by yzslab** [comment]
Hi, please take a look the F.A.Q. part of this README:
https://github.com/graphdeco-inria/gaussian-splatting#faq
